"""Test the relationship between the HTP abstraction proxy and psych label.

The input is the deduplicated sample-level score table generated by
``htp_shift_abstraction.py``.  The analysis compares label 00 and label 01
in the pooled data and separately within Child, College and Social domains.

Effect direction is always label 01 minus label 00:
  * positive Cliff's delta / median difference: label 01 is more abstract;
  * negative values: label 00 is more abstract.

Example:
    conda run -n yolo python htp_abstraction_label.py
"""

from __future__ import annotations

import argparse
import json
import math
import sys
import time
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import mannwhitneyu, rankdata


DOMAIN_ORDER = ["Child", "College", "Social"]
SCOPE_ORDER = ["All", *DOMAIN_ORDER]
LABEL_ORDER = ["00", "01"]
LABEL_COLORS = {"00": "#4C78A8", "01": "#E07A5F"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scores", default="output/htp_shift/abstraction_scores.csv",
        help="htp_shift_abstraction.py 生成的逐样本得分表",
    )
    parser.add_argument("--output-dir", default="output/htp_shift")
    parser.add_argument("--score-column", default="abstraction_score")
    parser.add_argument("--bootstrap", type=int, default=5000)
    parser.add_argument("--permutations", type=int, default=10000)
    parser.add_argument("--seed", type=int, default=20260811)
    return parser.parse_args()


def normalize_code(value: object) -> str:
    text = str(value).strip()
    if text.endswith(".0"):
        text = text[:-2]
    return text.zfill(2)


def load_scores(path: Path, score_column: str) -> pd.DataFrame:
    frame = pd.read_csv(path, dtype={"env": str, "label": str})
    required = {"path", "domain", "label", score_column}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"得分表缺少必要列: {sorted(missing)}")
    frame["label"] = frame["label"].map(normalize_code)
    if set(frame["label"]) != set(LABEL_ORDER):
        raise ValueError(f"心理类别应为 00/01，实际为 {sorted(frame['label'].unique())}")
    if not set(frame["domain"]).issubset(DOMAIN_ORDER):
        raise ValueError(f"发现未知 domain: {sorted(set(frame['domain']) - set(DOMAIN_ORDER))}")
    frame[score_column] = pd.to_numeric(frame[score_column], errors="coerce")
    if frame[score_column].isna().any():
        raise ValueError(f"{score_column} 有 {frame[score_column].isna().sum()} 个缺失值")
    if not frame[score_column].between(0, 1).all():
        raise ValueError(f"{score_column} 超出 [0,1]")
    if frame["path"].duplicated().any():
        raise ValueError("得分表中存在重复 path")
    return frame


def holm_adjust(p_values: list[float]) -> np.ndarray:
    p = np.asarray(p_values, dtype=float)
    order = np.argsort(p)
    adjusted_sorted = np.empty(len(p), dtype=float)
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, (len(p) - rank) * p[idx])
        adjusted_sorted[rank] = min(running, 1.0)
    adjusted = np.empty(len(p), dtype=float)
    adjusted[order] = adjusted_sorted
    return adjusted


def cliffs_delta_label01_minus_label00(x01: np.ndarray, x00: np.ndarray) -> float:
    u01 = mannwhitneyu(
        x01, x00, alternative="two-sided", method="asymptotic"
    ).statistic
    return float(2 * u01 / (len(x01) * len(x00)) - 1)


def bootstrap_effects(
    x01: np.ndarray,
    x00: np.ndarray,
    n_boot: int,
    rng: np.random.Generator,
):
    deltas = np.empty(n_boot, dtype=float)
    median_diffs = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        a = x01[rng.integers(0, len(x01), len(x01))]
        b = x00[rng.integers(0, len(x00), len(x00))]
        deltas[i] = cliffs_delta_label01_minus_label00(a, b)
        median_diffs[i] = np.median(a) - np.median(b)
    return (
        np.quantile(deltas, [0.025, 0.975]),
        np.quantile(median_diffs, [0.025, 0.975]),
    )


def frames_by_scope(frame: pd.DataFrame):
    yield "All", frame
    for domain in DOMAIN_ORDER:
        yield domain, frame[frame["domain"].eq(domain)].copy()


def group_summary(frame: pd.DataFrame, score_column: str) -> pd.DataFrame:
    rows = []
    for scope, subset in frames_by_scope(frame):
        for label in LABEL_ORDER:
            values = subset.loc[subset["label"].eq(label), score_column].to_numpy(float)
            rows.append({
                "scope": scope,
                "label": label,
                "n": len(values),
                "mean": np.mean(values),
                "std": np.std(values, ddof=1),
                "median": np.median(values),
                "q1": np.quantile(values, 0.25),
                "q3": np.quantile(values, 0.75),
            })
    return pd.DataFrame(rows)


def compare_labels(
    frame: pd.DataFrame,
    score_column: str,
    n_boot: int,
    seed: int,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    rows = []
    for scope, subset in frames_by_scope(frame):
        x00 = subset.loc[subset["label"].eq("00"), score_column].to_numpy(float)
        x01 = subset.loc[subset["label"].eq("01"), score_column].to_numpy(float)
        test = mannwhitneyu(x01, x00, alternative="two-sided", method="asymptotic")
        delta = cliffs_delta_label01_minus_label00(x01, x00)
        delta_ci, median_diff_ci = bootstrap_effects(x01, x00, n_boot, rng)
        rows.append({
            "scope": scope,
            "n_label00": len(x00),
            "n_label01": len(x01),
            "median_label00": np.median(x00),
            "median_label01": np.median(x01),
            "median_diff_label01_minus_label00": np.median(x01) - np.median(x00),
            "median_diff_ci_low": median_diff_ci[0],
            "median_diff_ci_high": median_diff_ci[1],
            "mann_whitney_U_label01": test.statistic,
            "p_raw": test.pvalue,
            "cliffs_delta_label01_minus_label00": delta,
            "cliffs_delta_ci_low": delta_ci[0],
            "cliffs_delta_ci_high": delta_ci[1],
            # Probability that a randomly chosen label-01 score exceeds a
            # randomly chosen label-00 score, with half credit for ties.
            "auc_label01_from_abstraction": (delta + 1) / 2,
        })
    result = pd.DataFrame(rows)
    result["p_holm_all_four"] = holm_adjust(result["p_raw"].tolist())
    result["p_holm_within_domains"] = np.nan
    domain_mask = result["scope"].isin(DOMAIN_ORDER)
    result.loc[domain_mask, "p_holm_within_domains"] = holm_adjust(
        result.loc[domain_mask, "p_raw"].tolist()
    )
    return result


def nested_f_stat(y: np.ndarray, x_reduced: np.ndarray, x_full: np.ndarray) -> float:
    beta_reduced = np.linalg.lstsq(x_reduced, y, rcond=None)[0]
    beta_full = np.linalg.lstsq(x_full, y, rcond=None)[0]
    residual_reduced = y - x_reduced @ beta_reduced
    residual_full = y - x_full @ beta_full
    rss_reduced = float(residual_reduced @ residual_reduced)
    rss_full = float(residual_full @ residual_full)
    df_num = x_full.shape[1] - x_reduced.shape[1]
    df_den = len(y) - x_full.shape[1]
    numerator = max((rss_reduced - rss_full) / df_num, 0.0)
    denominator = rss_full / df_den
    return numerator / denominator if denominator > 0 else math.inf


def freedman_lane_test(
    y: np.ndarray,
    x_reduced: np.ndarray,
    x_full: np.ndarray,
    strata: np.ndarray,
    n_perm: int,
    rng: np.random.Generator,
):
    observed = nested_f_stat(y, x_reduced, x_full)
    beta_reduced = np.linalg.lstsq(x_reduced, y, rcond=None)[0]
    fitted = x_reduced @ beta_reduced
    residuals = y - fitted
    null = np.empty(n_perm, dtype=float)
    unique_strata = np.unique(strata)
    for b in range(n_perm):
        permuted = residuals.copy()
        for stratum in unique_strata:
            idx = np.flatnonzero(strata == stratum)
            permuted[idx] = rng.permutation(residuals[idx])
        y_perm = fitted + permuted
        null[b] = nested_f_stat(y_perm, x_reduced, x_full)
    p = (1 + np.sum(null >= observed)) / (n_perm + 1)
    return observed, float(p), null


def rank_permutation_analysis(
    frame: pd.DataFrame,
    score_column: str,
    n_perm: int,
    seed: int,
):
    work = frame.copy()
    work["rank_pct_within_domain"] = work.groupby("domain")[score_column].transform(
        lambda s: rankdata(s.to_numpy(), method="average") / (len(s) + 1)
    )
    y = work["rank_pct_within_domain"].to_numpy(float)
    label01 = work["label"].eq("01").to_numpy(float)
    college = work["domain"].eq("College").to_numpy(float)
    social = work["domain"].eq("Social").to_numpy(float)
    strata = work["domain"].to_numpy(str)
    intercept = np.ones(len(work))

    x_domain = np.column_stack([intercept, college, social])
    x_common_label = np.column_stack([x_domain, label01])
    x_interaction = np.column_stack([
        x_common_label, label01 * college, label01 * social,
    ])
    rng = np.random.default_rng(seed)
    f_common, p_common, null_common = freedman_lane_test(
        y, x_domain, x_common_label, strata, n_perm, rng
    )
    f_interaction, p_interaction, null_interaction = freedman_lane_test(
        y, x_common_label, x_interaction, strata, n_perm, rng
    )

    beta = np.linalg.lstsq(x_interaction, y, rcond=None)[0]
    effects = pd.DataFrame({
        "domain": DOMAIN_ORDER,
        "mean_rank_effect_label01_minus_label00": [
            beta[3], beta[3] + beta[4], beta[3] + beta[5],
        ],
    })
    tests = pd.DataFrame([
        {
            "test": "common_label_effect_controlling_domain",
            "F": f_common,
            "df_num": 1,
            "df_den": len(y) - x_common_label.shape[1],
            "permutations": n_perm,
            "p_permutation": p_common,
            "null_mean": np.mean(null_common),
            "null_q95": np.quantile(null_common, 0.95),
        },
        {
            "test": "domain_x_label_interaction",
            "F": f_interaction,
            "df_num": 2,
            "df_den": len(y) - x_interaction.shape[1],
            "permutations": n_perm,
            "p_permutation": p_interaction,
            "null_mean": np.mean(null_interaction),
            "null_q95": np.quantile(null_interaction, 0.95),
        },
    ])
    return tests, effects


def bootstrap_group_medians(
    frame: pd.DataFrame,
    score_column: str,
    n_boot: int,
    seed: int,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    rows = []
    for domain in DOMAIN_ORDER:
        for label in LABEL_ORDER:
            values = frame.loc[
                frame["domain"].eq(domain) & frame["label"].eq(label), score_column
            ].to_numpy(float)
            boot = np.empty(n_boot, dtype=float)
            for b in range(n_boot):
                sample = values[rng.integers(0, len(values), len(values))]
                boot[b] = np.median(sample)
            rows.append({
                "domain": domain,
                "label": label,
                "n": len(values),
                "median": np.median(values),
                "median_ci_low": np.quantile(boot, 0.025),
                "median_ci_high": np.quantile(boot, 0.975),
            })
    return pd.DataFrame(rows)


def set_plot_style():
    matplotlib.rcParams.update({
        "font.sans-serif": ["Microsoft YaHei", "SimHei", "DejaVu Sans"],
        "axes.unicode_minus": False,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "text.color": "#222222",
        "axes.labelcolor": "#222222",
    })
    sns.set_theme(style="whitegrid", rc={
        "font.sans-serif": ["Microsoft YaHei", "SimHei", "DejaVu Sans"],
        "axes.unicode_minus": False,
        "grid.color": "#E8E8E8",
        "grid.linewidth": 0.7,
    })


def format_p(p: float) -> str:
    return f"{p:.2e}" if p < 0.001 else f"{p:.3f}"


def plot_four_panel(
    frame: pd.DataFrame,
    tests: pd.DataFrame,
    score_column: str,
    output_dir: Path,
):
    fig, axes = plt.subplots(2, 2, figsize=(11.8, 9.1), sharey=True)
    axes = axes.ravel()
    for ax, (scope, subset) in zip(axes, frames_by_scope(frame)):
        sns.violinplot(
            data=subset, x="label", y=score_column, hue="label",
            order=LABEL_ORDER, hue_order=LABEL_ORDER, palette=LABEL_COLORS,
            legend=False, inner=None, cut=0, density_norm="width",
            saturation=0.82, linewidth=0.9, ax=ax,
        )
        sns.boxplot(
            data=subset, x="label", y=score_column, order=LABEL_ORDER,
            width=0.18, showfliers=False, color="white",
            boxprops={"facecolor": "white", "edgecolor": "#333333", "alpha": 0.88},
            medianprops={"color": "#111111", "linewidth": 1.5},
            whiskerprops={"color": "#333333", "linewidth": 0.9},
            capprops={"color": "#333333", "linewidth": 0.9}, ax=ax,
        )
        row = tests[tests["scope"].eq(scope)].iloc[0]
        p_col = "p_holm_all_four" if scope == "All" else "p_holm_within_domains"
        p_value = row[p_col]
        direction = row["cliffs_delta_label01_minus_label00"]
        ax.text(
            0.5, 0.985,
            f"Cliff's delta(01-00)={direction:+.3f}  |  Holm p={format_p(p_value)}  |  AUC(01)={row.auc_label01_from_abstraction:.3f}",
            transform=ax.transAxes, ha="center", va="top", fontsize=8.7,
            bbox={"boxstyle": "round,pad=0.28", "facecolor": "white", "edgecolor": "#C8C8C8"},
        )
        counts = subset["label"].value_counts()
        ax.set_xticks([0, 1], labels=[f"Label 00\n(n={counts['00']})", f"Label 01\n(n={counts['01']})"])
        ax.set_title(scope, fontsize=12, weight="semibold")
        ax.set_xlabel("")
        ax.set_ylabel("Abstraction proxy" if ax in [axes[0], axes[2]] else "")
        ax.set_ylim(0, 1.06)
        sns.despine(ax=ax)
    fig.suptitle("HTP abstraction proxy by psychological label", fontsize=15, weight="semibold", y=0.99)
    fig.text(
        0.5, 0.955,
        "Effect direction: positive delta means label 01 has higher abstraction; domain tests use Holm correction",
        ha="center", va="center", fontsize=9.5, color="#555555",
    )
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    for suffix in ["png", "svg"]:
        fig.savefig(output_dir / f"abstraction_vs_label_four_panel.{suffix}", dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_interaction(
    median_ci: pd.DataFrame,
    permutation_tests: pd.DataFrame,
    output_dir: Path,
):
    fig, ax = plt.subplots(figsize=(8.7, 5.8))
    offsets = {"00": -0.07, "01": 0.07}
    markers = {"00": "o", "01": "s"}
    linestyles = {"00": "-", "01": "--"}
    x_base = np.arange(len(DOMAIN_ORDER), dtype=float)
    for label in LABEL_ORDER:
        subset = median_ci[median_ci["label"].eq(label)].set_index("domain").loc[DOMAIN_ORDER]
        y = subset["median"].to_numpy(float)
        lo = subset["median_ci_low"].to_numpy(float)
        hi = subset["median_ci_high"].to_numpy(float)
        x = x_base + offsets[label]
        ax.errorbar(
            x, y, yerr=np.vstack([y - lo, hi - y]),
            color=LABEL_COLORS[label], marker=markers[label], linestyle=linestyles[label],
            linewidth=1.6, markersize=6.5, capsize=4, label=f"Label {label}",
        )
    interaction = permutation_tests[
        permutation_tests["test"].eq("domain_x_label_interaction")
    ].iloc[0]
    ax.text(
        0.99, 0.98,
        f"Domain × label interaction: F={interaction.F:.2f}, permutation p={format_p(interaction.p_permutation)}",
        transform=ax.transAxes, ha="right", va="top", fontsize=9,
        bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "edgecolor": "#BBBBBB"},
    )
    ax.set_xticks(x_base, labels=DOMAIN_ORDER)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Population domain")
    ax.set_ylabel("Median abstraction proxy")
    ax.set_title("Domain-specific relationship between abstraction and psychological label", fontsize=13, pad=12)
    ax.legend(frameon=False, title="Psychological label", loc="upper right", bbox_to_anchor=(1, 0.84))
    sns.despine(ax=ax)
    fig.tight_layout()
    for suffix in ["png", "svg"]:
        fig.savefig(output_dir / f"abstraction_label_interaction.{suffix}", dpi=300, bbox_inches="tight")
    plt.close(fig)


def decision_text(tests: pd.DataFrame, permutation_tests: pd.DataFrame) -> str:
    within = tests[tests["scope"].isin(DOMAIN_ORDER)]
    significant = within[within["p_holm_within_domains"] < 0.05]
    directions = np.sign(significant["cliffs_delta_label01_minus_label00"].to_numpy())
    interaction_p = permutation_tests.loc[
        permutation_tests["test"].eq("domain_x_label_interaction"), "p_permutation"
    ].iloc[0]
    if len(significant) == 0:
        return (
            "三个域内均未检测到经过 Holm 校正的 A–Y 关系。当前结果更接近 nuisance/domain factor，"
            "但仍需用下游标签性能验证消除操作。"
        )
    if interaction_p < 0.05:
        return (
            "至少一个域内存在显著 A–Y 关系，且 domain × label 交互显著，"
            "说明该关系随域变化。不能全局消除 abstraction；全局投影可能删除域内标签信息。"
        )
    return (
        "至少一个域内存在显著 A–Y 关系，abstraction proxy 含有标签信息。"
        "不能在没有下游消融实验的情况下将其整体删除。"
    )


def write_summary(
    source: Path,
    tests: pd.DataFrame,
    group_stats: pd.DataFrame,
    permutation_tests: pd.DataFrame,
    output_dir: Path,
    runtime_seconds: float,
):
    decision = decision_text(tests, permutation_tests)
    lines = [
        "# Abstraction–psychological-label relationship",
        "",
        f"Source: `{source.resolve()}`",
        "",
        "Effect direction is label 01 minus label 00. Positive values mean label 01 has higher abstraction.",
        "",
        "| Scope | Label 00 median [IQR] | Label 01 median [IQR] | δ(01−00) [95% CI] | AUC(01) | Holm p |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for scope in SCOPE_ORDER:
        test = tests[tests["scope"].eq(scope)].iloc[0]
        s00 = group_stats[(group_stats["scope"].eq(scope)) & (group_stats["label"].eq("00"))].iloc[0]
        s01 = group_stats[(group_stats["scope"].eq(scope)) & (group_stats["label"].eq("01"))].iloc[0]
        p = test.p_holm_all_four if scope == "All" else test.p_holm_within_domains
        lines.append(
            f"| {scope} | {s00['median']:.3f} [{s00.q1:.3f}, {s00.q3:.3f}] | "
            f"{s01['median']:.3f} [{s01.q1:.3f}, {s01.q3:.3f}] | "
            f"{test.cliffs_delta_label01_minus_label00:+.3f} "
            f"[{test.cliffs_delta_ci_low:+.3f}, {test.cliffs_delta_ci_high:+.3f}] | "
            f"{test.auc_label01_from_abstraction:.3f} | {p:.6g} |"
        )
    lines.extend(["", "## Rank-based permutation models", ""])
    for row in permutation_tests.itertuples(index=False):
        lines.append(
            f"- `{row.test}`: F({int(row.df_num)}, {int(row.df_den)})={row.F:.3f}, "
            f"permutation p={row.p_permutation:.6g} ({int(row.permutations)} permutations)."
        )
    lines.extend([
        "",
        "## Decision",
        "",
        decision,
        "",
        "The score remains a Qwen-derived proxy and has not been validated against blinded human ratings.",
        "",
        f"Runtime: {runtime_seconds:.1f} seconds.",
    ])
    (output_dir / "abstraction_label_analysis.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main():
    args = parse_args()
    started = time.time()
    source = Path(args.scores).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"[1/4] Loading {source}", flush=True)
    frame = load_scores(source, args.score_column)
    audit = frame.groupby(["domain", "label"]).size().rename("n").reset_index()
    audit.to_csv(output_dir / "abstraction_label_audit.csv", index=False)
    print(audit.to_string(index=False), flush=True)

    print("[2/4] Mann-Whitney, Cliff's delta and bootstrap intervals", flush=True)
    group_stats = group_summary(frame, args.score_column)
    tests = compare_labels(frame, args.score_column, args.bootstrap, args.seed)
    median_ci = bootstrap_group_medians(
        frame, args.score_column, args.bootstrap, args.seed + 1
    )
    group_stats.to_csv(output_dir / "abstraction_label_group_summary.csv", index=False)
    tests.to_csv(output_dir / "abstraction_label_tests.csv", index=False)
    median_ci.to_csv(output_dir / "abstraction_label_median_ci.csv", index=False)

    print("[3/4] Domain-adjusted rank and domain-by-label interaction tests", flush=True)
    permutation_tests, rank_effects = rank_permutation_analysis(
        frame, args.score_column, args.permutations, args.seed + 2
    )
    permutation_tests.to_csv(output_dir / "abstraction_label_permutation_tests.csv", index=False)
    rank_effects.to_csv(output_dir / "abstraction_label_rank_effects.csv", index=False)

    print("[4/4] Rendering figures and summary", flush=True)
    set_plot_style()
    plot_four_panel(frame, tests, args.score_column, output_dir)
    plot_interaction(median_ci, permutation_tests, output_dir)
    runtime = time.time() - started
    write_summary(
        source, tests, group_stats, permutation_tests, output_dir, runtime
    )
    run_metadata = {
        "python": sys.version,
        "python_executable": sys.executable,
        "scores": str(source),
        "score_column": args.score_column,
        "bootstrap": args.bootstrap,
        "permutations": args.permutations,
        "seed": args.seed,
        "runtime_seconds": runtime,
    }
    (output_dir / "abstraction_label_runtime.json").write_text(
        json.dumps(run_metadata, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(tests.to_string(index=False), flush=True)
    print(permutation_tests.to_string(index=False), flush=True)
    print(decision_text(tests, permutation_tests), flush=True)
    print(f"Done in {runtime:.1f}s", flush=True)


if __name__ == "__main__":
    main()
